# gRPC服务配置
grpc_server:
  host: "0.0.0.0"
  port: 9004
  timeout: 30s

# 数据库配置
database:
  host: "47.99.147.94"
  port: 5432
  database: "inventory-service"
  user: "postgres"
  password: "wdh961100"
  ssl_mode: "disable"
  timezone: "Asia/Shanghai"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600s

# Redis配置
redis:
  host: "47.99.147.94"
  port: 6379
  password: ""
  database: 3
  pool_size: 10
  min_idle_conns: 5

# 日志配置
log:
  level: "info"
  format: "json"
  output: "stdout"

# 监控配置
monitoring:
  enabled: true
  service_name: "inventory-service"

# 链路追踪配置
tracing:
  enabled: true
  service_name: "inventory-service"
  jaeger:
    endpoint: "http://localhost:14268/api/traces"

# 服务依赖配置
services:
  order_service:
    host: "localhost"
    port: 9002
  product_service:
    host: "localhost"
    port: 9001
  user_service:
    host: "localhost"
    port: 9000
