// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"context"
	"github.com/people257/poor-guy-shop/common/server/config"
	"github.com/people257/poor-guy-shop/common/server/internal"
)

// Injectors from wire.go:

func InitializeServer(ctx context.Context, cfg *config.GrpcServerConfig) (*Sever, func()) {
	serverConfig := config.GetServerConfig(cfg)
	logConfig := config.GetLogConfig(cfg)
	logger, cleanup := internal.NewZapLogger(serverConfig, logConfig)
	server, cleanup2 := internal.NewGrpcServer(cfg, logger)
	register := internal.NewRegister(serverConfig)
	sever := newServer(cfg, server, register)
	return sever, func() {
		cleanup2()
		cleanup()
	}
}
