// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"cnb.cool/cymirror/ces-services/common/project-template/cmd/grpc/internal/config"
	"cnb.cool/cymirror/ces-services/common/server"
	"context"
)

// Injectors from wire.go:

func InitializeApplication(ctx context.Context, configPath2 string) (*Application, func()) {
	configConfig := config.MustLoad(configPath2)
	grpcServerConfig := config.GetGrpcServerConfig(configConfig)
	serverServer, cleanup := server.InitializeServer(ctx, grpcServerConfig)
	application := NewApplication(configConfig, serverServer)
	return application, func() {
		cleanup()
	}
}
