grpc_server_config:
  host: "0.0.0.0"
  port: 9002

database:
  host: localhost
  port: 5432
  username: postgres
  password: password
  database: poor_guy_shop_order
  sslmode: disable
  timezone: Asia/Shanghai

redis:
  addr: localhost:6379
  password: ""
  db: 0

services:
  user_service:
    host: localhost
    port: 9001
  product_service:
    host: localhost
    port: 9000
